import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const prod = process.argv[2] === 'production';
const context = await esbuild.context({
  banner: { js: '/* Generated by esbuild. Source lives in src/. */' },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: ['obsidian', 'electron', ...builtinModules],
  alias: {
    'buffer/index': 'buffer',
    'isomorphic-ws': 'isomorphic-ws/node.js',
    'ws': './node_modules/ws/index.js',
  },
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
