import type { AiRssSettings, PluginState } from './types';
import { SUPPLEMENTARY_FILE_TYPES } from './attachments';
import { DEFAULT_PROVIDER_CONFIGS } from './provider-settings';
import { EDGE_TTS_DEFAULT_VOICE } from './edge-tts-voices';

export const DEFAULT_SETTINGS: AiRssSettings = {
  feeds: [
    {
      id: 'arxiv-cs-ai',
      url: 'https://export.arxiv.org/rss/cs.AI',
      name: 'arXiv · Artificial Intelligence',
      enabled: true,
    },
  ],
  profiles: [
    {
      id: 'default',
      name: '默认研究方向',
      description: 'Large Language Model Agents and Multi-agent systems',
      enabled: true,
    },
  ],
  provider: { ...DEFAULT_PROVIDER_CONFIGS.openai },
  providerConfigs: structuredClone(DEFAULT_PROVIDER_CONFIGS),
  keywordFilter: true,
  keepIrrelevant: false,
  maxItemsPerFeed: 50,
  batchSize: 8,
  profileReanalysisDays: 1,
  readRetentionDays: 30,
  unreadRetentionDays: 90,
  outputFolder: 'AI RSS Reader',
  literatureFolderTemplate: '{author} - {year} - {title}',
  openNoteAfterSingleSave: true,
  batchCaptureIntervalSeconds: 1.5,
  extractFullText: true,
  downloadBibtex: true,
  downloadPdf: true,
  downloadSupplementary: true,
  supplementaryFileTypes: [...SUPPLEMENTARY_FILE_TYPES],
  downloadPeerReview: true,
  peerReviewFileTypes: [...SUPPLEMENTARY_FILE_TYPES],
  ezProxyEnabled: false,
  ezProxyPrefix: 'https://sutd.idm.oclc.org/login?url=$@',
  ezProxyCookieHeader: '',
  ezProxyLastAuthenticated: '',
  noteNameFormat: '{{citekey}}',
  noteContentFormat: '# {{title}}\n\n> [!info] 文献\n> {{authors}} · {{journal}} · {{year}}\n> [打开原文]({{url}}){{doiLink}}\n\n{{filesSection}}{{warningsSection}}\n## AI 分析\n\n{{aiAnalysis}}\n\n## 正文\n\n{{content}}',
  noteProperties: [
    { name: 'title', value: '{{title}}', type: 'text' },
    { name: 'source', value: '{{url}}', type: 'text' },
    { name: 'authors', value: '{{authors}}', type: 'multitext' },
    { name: 'published', value: '{{published}}', type: 'date' },
    { name: 'created', value: '{{date}}', type: 'date' },
    { name: 'journal', value: '{{journal}}', type: 'text' },
    { name: 'year', value: '{{year}}', type: 'number' },
    { name: 'doi', value: '{{doi}}', type: 'text' },
    { name: 'citekey', value: '{{citekey}}', type: 'text' },
    { name: 'profiles', value: '{{profiles}}', type: 'multitext' },
    { name: 'tags', value: 'ai-rss-reader', type: 'multitext' },
  ],
  mineruToken: '',
  mineruModelVersion: 'vlm',
  mineruLanguage: 'en',
  mineruOcr: false,
  mineruEnableTable: true,
  mineruEnableFormula: true,
  mineruSaveMarkdown: true,
  mineruSaveContentListJson: true,
  mineruSaveLayoutJson: true,
  mineruSaveModelJson: false,
  mineruSaveImages: true,
  mineruSaveOtherFiles: false,
  audioTutorLanguage: '中文（保留必要的英文术语）',
  audioTutorLearnerBackground: '具有凝聚态理论物理基础',
  audioTutorTargetMinutes: 25,
  edgeTtsVoice: EDGE_TTS_DEFAULT_VOICE,
  edgeTtsRate: 0,
  edgeTtsPitch: 0,
  edgeTtsVolume: 0,
};

export const DEFAULT_STATE: PluginState = {
  settings: DEFAULT_SETTINGS,
  articles: [],
  seenLinks: [],
  lastFetchedAt: '',
  lastLiteratureSaveFolder: '',
  tableColumnWidths: {
    preview: 260,
    select: 38,
    title: 350,
    source: 220,
    profiles: 110,
    reason: 267,
    date: 110,
  },
  audioTutorPlaybackPositions: {},
};
